<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>FLYERALARM - Reseller Api</title>
    <link href="res/css/simple.css" rel="stylesheet" type="text/css">
</head>
<body>

<header>
    <div class="service-bar">
        <div class="top-bar">
            <span class="service-bar-text">Reseller Api Example</span>
        </div>
    </div>
    <div id="toolbar">
        <div class="top-bar">
            <span class="toolbar-text">FLYERALARM</span>
        </div>
    </div>

</header>

<main>

    <?php
        if( $response instanceof flyeralarm\ResellerApiExample\view\Response ){
            echo '
            <div id="wrapper">
                <div class="productBox">
                    <h1>'.$response->getHeader().'</h1>
                    '.$response->getText().'<br>
                </div>
            </div>
            ';

        }
    ?>

</main>


</body>
</html>